Update sudoku.py
marina-kuzmina/programming pull request #5
Opened 2021-11-20 20:15 UTC by marina-kuzmina

2021-12-30 08:45 UTC, anastasiiaCher requested changes

2021-12-30 08:45 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return groups
Это все можно записать в одну строку

2021-12-30 08:45 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return block
Это можно записать одним списковым включением

2021-12-30 08:45 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return ()
Если хотите вернуть ничего, так и пишите - `return None`

2021-12-30 08:45 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return []
Тоже лучше вернуть `None`

2021-12-30 08:45 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return grid
Вот это очень хорошо

2021-12-30 10:04 UTC, marina-kuzmina commented on homework02/sudoku.py
> +    return ()
mypy пишет, что так нельзя и это Incompatible return value type

2022-01-17 03:24 UTC, anastasiiaCher reviewed
C `mypy` можно договоритсья)
14.

2022-06-30 13:15 UTC, merged